/** Ciudades donde corre un local. El dueño escribe la suya; esto es atajo. */
export const AR_CITIES = [
  "CABA",
  "La Plata",
  "Mar del Plata",
  "Bahía Blanca",
  "Córdoba",
  "Rosario",
  "Santa Fe",
  "Paraná",
  "Mendoza",
  "San Juan",
  "San Luis",
  "San Miguel de Tucumán",
  "Salta",
  "Jujuy",
  "Santiago del Estero",
  "Catamarca",
  "La Rioja",
  "Neuquén",
  "Cipolletti",
  "Bariloche",
  "Comodoro Rivadavia",
  "Rawson",
  "Trelew",
  "Río Gallegos",
  "Ushuaia",
  "Posadas",
  "Corrientes",
  "Resistencia",
  "Formosa",
  "San Salvador de Jujuy",
  "Villa María",
  "Río Cuarto",
  "San Rafael",
  "Tandil",
  "Olavarría",
  "Pergamino",
  "Campana",
  "Zárate",
  "Luján",
  "Quilmes",
  "Avellaneda",
  "Lanús",
  "Lomas de Zamora",
  "Morón",
  "San Justo",
  "San Miguel",
  "Tigre",
  "Pilar",
  "Escobar",
  "José C. Paz",
];
