/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivarRouteImport } from './routes/activar'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ApiDeskInboxRouteImport } from './routes/api/desk-inbox'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWooIssueRouteImport } from './routes/api/woo/issue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivarRoute = ActivarRouteImport.update({
  id: '/activar',
  path: '/activar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskInboxRoute = ApiDeskInboxRouteImport.update({
  id: '/api/desk-inbox',
  path: '/api/desk-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWooIssueRoute = ApiWooIssueRouteImport.update({
  id: '/api/woo/issue',
  path: '/api/woo/issue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/estudio': typeof EstudioRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/terminos': typeof TerminosRoute
  '/api/desk-inbox': typeof ApiDeskInboxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/woo/issue': typeof ApiWooIssueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/estudio': typeof EstudioRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/terminos': typeof TerminosRoute
  '/api/desk-inbox': typeof ApiDeskInboxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/woo/issue': typeof ApiWooIssueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activar': typeof ActivarRoute
  '/estudio': typeof EstudioRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/terminos': typeof TerminosRoute
  '/api/desk-inbox': typeof ApiDeskInboxRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/woo/issue': typeof ApiWooIssueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activar'
    | '/estudio'
    | '/login'
    | '/recuperar'
    | '/terminos'
    | '/api/desk-inbox'
    | '/api/auth/$'
    | '/api/woo/issue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activar'
    | '/estudio'
    | '/login'
    | '/recuperar'
    | '/terminos'
    | '/api/desk-inbox'
    | '/api/auth/$'
    | '/api/woo/issue'
  id:
    | '__root__'
    | '/'
    | '/activar'
    | '/estudio'
    | '/login'
    | '/recuperar'
    | '/terminos'
    | '/api/desk-inbox'
    | '/api/auth/$'
    | '/api/woo/issue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivarRoute: typeof ActivarRoute
  EstudioRoute: typeof EstudioRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  TerminosRoute: typeof TerminosRoute
  ApiDeskInboxRoute: typeof ApiDeskInboxRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWooIssueRoute: typeof ApiWooIssueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activar': {
      id: '/activar'
      path: '/activar'
      fullPath: '/activar'
      preLoaderRoute: typeof ActivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk-inbox': {
      id: '/api/desk-inbox'
      path: '/api/desk-inbox'
      fullPath: '/api/desk-inbox'
      preLoaderRoute: typeof ApiDeskInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/woo/issue': {
      id: '/api/woo/issue'
      path: '/api/woo/issue'
      fullPath: '/api/woo/issue'
      preLoaderRoute: typeof ApiWooIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivarRoute: ActivarRoute,
  EstudioRoute: EstudioRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  TerminosRoute: TerminosRoute,
  ApiDeskInboxRoute: ApiDeskInboxRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWooIssueRoute: ApiWooIssueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
